// examples/solid-ssr-ts-v1/pages/index/+Page.tsx
import type { Component } from "solid-js";
import { Counter } from "./Counter";

const Page: Component = () => {
  return (
    <>
      <h1>Welcome</h1>
      <div>
        This page is:
        <ul>
          <li>Rendered to HTML.</li>
          <li>
            Interactive. <Counter />
          </li>
        </ul>
      </div>
    </>
  );
};
export default Page;

// examples/react-full-ts-v1/pages/index/+Page.tsx
export default Page;

import React from "react";
import { navigate } from "vite-plugin-ssr/client/router";
import { Counter } from "../../components/Counter";

function Page() {
  return (
    <>
      <h1>
        Welcome to <code>vite-plugin-ssr</code>
      </h1>
      This page is:
      <ul>
        <li>Rendered to HTML.</li>
        <li>
          Interactive. <Counter />
        </li>
      </ul>
      <p>
        <button
          onClick={() => {
            const randomIndex = Math.floor(Math.random() * 3);
            navigate(["/markdown", "/star-wars", "/hello/alice"][randomIndex]);
          }}
        >
          Random Page
        </button>
      </p>
    </>
  );
}
