// examples/ts-ssr-react-cloudflare-workers-full-new/src/renderer/PageLayout.tsx
import React from "react";
import "./PageLayout.css";
import { PageContext } from "./types";
import { PageContextProvider } from "./usePageContext";

const PageLayout = ({
  pageContext,
  children,
}: {
  pageContext: PageContext;
  children: React.ReactNode;
}) => {
  return (
    <React.StrictMode>
      <PageContextProvider pageContext={pageContext}>
        <Layout>
          <Sidebar>
            <a className="navitem" href="/">
              Home
            </a>
            <a className="navitem" href="/about">
              About
            </a>
            <a className="navitem" href="/star-wars">
              Star Wars
            </a>
          </Sidebar>
          <Content>{children}</Content>
        </Layout>
      </PageContextProvider>
    </React.StrictMode>
  );
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div
      style={{
        display: "flex",
        maxWidth: 900,
        margin: "auto",
      }}
    >
      {children}
    </div>
  );
};

const Sidebar = ({ children }: { children: React.ReactNode }) => {
  return (
    <div
      style={{
        padding: 20,
        paddingTop: 42,
        flexShrink: 0,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        lineHeight: "1.8em",
      }}
    >
      {children}
    </div>
  );
};

const Content = ({ children }: { children: React.ReactNode }) => {
  return (
    <div
      style={{
        padding: 20,
        paddingBottom: 50,
        borderLeft: "2px solid #eee",
        minHeight: "100vh",
      }}
    >
      {children}
    </div>
  );
};

export { PageLayout };

// examples/solid-ssr-ts-v1/renderer/PageLayout.tsx
import type { JSX, Component } from "solid-js";
import { Link } from "./Link";
import logo from "./logo.svg";
import "./PageLayout.css";
import { PageContextProvider, usePageContext } from "./usePageContext";
import type { PageContext } from "./types";
import type { Store } from "solid-js/store";
import { Dynamic } from "solid-js/web";

export { PageLayout };

interface Props {
  pageContext: Store<PageContext>;
}
interface Children {
  children: JSX.Element;
}

const PageLayout: Component<Props> = (props) => {
  return (
    <PageContextProvider pageContext={props.pageContext}>
      <Layout>
        <Sidebar>
          <Logo />
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
        </Sidebar>
        <Content>
          <Page />
        </Content>
      </Layout>
    </PageContextProvider>
  );
};

function Page() {
  const pageContext = usePageContext();
  return (
    <>
      <Dynamic
        component={pageContext.Page}
        {...(pageContext.pageProps ?? {})}
      />
    </>
  );
}

const Layout: Component<Children> = (props) => {
  return (
    <div
      style={{
        display: "flex",
        "max-width": "900px",
        margin: "auto",
      }}
    >
      {props.children}
    </div>
  );
};

const Sidebar: Component<Children> = (props) => {
  return (
    <div
      style={{
        padding: "20px",
        "flex-shrink": 0,
        display: "flex",
        "flex-direction": "column",
        "align-items": "center",
        "line-height": "1.8em",
      }}
    >
      {props.children}
    </div>
  );
};

const Content: Component<Children> = (props) => {
  return (
    <div
      style={{
        padding: "20px",
        "padding-bottom": "50px",
        "border-left": "2px solid #eee",
        "min-height": "100vh",
      }}
    >
      {props.children}
    </div>
  );
};

const Logo: Component = () => {
  return (
    <div
      style={{
        "margin-top": "20px",
        "margin-bottom": "10px",
      }}
    >
      <a href="/">
        <img src={logo} height={64} width={64} alt="logo" />
      </a>
    </div>
  );
};
