// examples/ts-ssr-react-custom-preload/src/renderer/types.ts
import type {
  PageContextBuiltIn,
  /*
// When using Client Routing https://vite-plugin-ssr.com/clientRouting
PageContextBuiltInClientWithClientRouting as PageContextBuiltInClient
/*/
  // When using Server Routing
  PageContextBuiltInClientWithServerRouting as PageContextBuiltInClient,
} from "vike/types";

type PageProps = Record<string, unknown>;
type Page = (pageProps: PageProps) => React.ReactElement;

type PageContextCustom = {
  Page: Page;
  pageProps?: PageProps;
  urlPathname: string;
  exports: {
    documentProps?: {
      title?: string;
      description?: string;
    };
  };
};

type PageContextServer = PageContextBuiltIn<Page> & PageContextCustom;
type PageContextClient = PageContextBuiltInClient<Page> & PageContextCustom;

type PageContext = PageContextClient | PageContextServer;

export type {
  PageContext,
  PageContextClient,
  PageContextCustom,
  PageContextServer,
  PageProps,
};

// examples/solid-ssr-ts-v1/renderer/types.ts
import { Component } from "solid-js";
import type { PageContextBuiltIn } from "vite-plugin-ssr/types";
export type PageProps = {};
type Page = Component<PageProps>;
export type PageContext = PageContextBuiltIn<Page> & {
  pageProps: PageProps;
  documentProps?: {
    title?: string;
    description?: string;
  };
};
