// examples/ts-ssr-react-graphql-urql/src/pages/index/index.page.tsx
import { gql, useQuery } from "urql";
import { Counter } from "./Counter";

const query = gql`
  {
    countries {
      code
      name
    }
  }
`;

const Page = () => {
  const [result] = useQuery({ query });
  const { data, fetching, error } = result;

  return (
    <>
      <h1>Counter</h1>
      <Counter />
      <h1>Countries</h1>
      <>
        {fetching && <p>Loading...</p>}
        {error && <p>Oh no... {error.message}</p>}
        {data && (
          <ul>
            {data.countries.map((country: { name: string; code: string }) => (
              <li key={country.code}>{country.name}</li>
            ))}
          </ul>
        )}
      </>
    </>
  );
};

export { Page };

// examples/graphql-apollo-vue/pages/index/index.page.vue
<template>
  <div>
    <h1>Welcome to Vue 3 Apollo example</h1>
    <p>List of countries.</p>
    <ul>
      <li v-for="country in result.countries" :key="country.code">
        {{ country.name }}
      </li>
    </ul>
  </div>
</template>

<script>
import { gql } from "@apollo/client";
import { useQuery, useResult } from "@vue/apollo-composable";
export default {
  setup() {
    const { result } = useQuery(gql`
      {
        countries {
          code
          name
        }
      }
    `);
    return { result };
  },
};
</script>
