// examples/ts-ssr-react-streaming/src/renderer/+onRenderClient.tsx
// https://vite-plugin-ssr.com/onRenderClient
import { hydrateRoot } from "react-dom/client";
import { PageLayout } from "./PageLayout";
import { PageContext } from "./types";

const onRenderClient = async (pageContext: PageContext) => {
  const { Page, pageProps } = pageContext;
  hydrateRoot(
    document.getElementById("page-view")!,
    <PageLayout>
      <Page {...pageProps} />
    </PageLayout>,
  );
};

export default onRenderClient;

// examples/solid-spa-ts-v1/renderer/+onRenderClient.tsx
// https://vite-plugin-ssr.com/onRenderClient
export default onRenderClient;

import { render } from "solid-js/web";
import type { PageContextClient } from "./types";

/**
 * A function that disposes previously rendered pages.
 *
 * If the function is not executed, each route change will
 * append a page to the DOM without clearing (disposing)
 * the previous one.
 */
let disposePreviousPage: () => void;

const onRenderClient = async (pageContext: PageContextClient) => {
  const { Page } = pageContext;

  if (disposePreviousPage) {
    disposePreviousPage();
  }

  // render the page and save the dispose function of that page
  disposePreviousPage = render(() => <Page />, document.getElementById("root"));
};
