// examples/js-ssr-react-router-new/renderer/+onRenderClient.jsx
// https://vite-plugin-ssr.com/onRenderClient
export default onRenderClient;

import React from "react";
import { hydrateRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";

async function onRenderClient(pageContext) {
  const { Page } = pageContext;
  hydrateRoot(
    document.getElementById("react-root"),
    <BrowserRouter>
      <Page {...pageContext.pageProps} />
    </BrowserRouter>,
  );
}

// examples/solid-spa-ts-v1/renderer/+onRenderClient.tsx
// https://vite-plugin-ssr.com/onRenderClient
export default onRenderClient;

import { render } from "solid-js/web";
import type { PageContextClient } from "./types";

/**
 * A function that disposes previously rendered pages.
 *
 * If the function is not executed, each route change will
 * append a page to the DOM without clearing (disposing)
 * the previous one.
 */
let disposePreviousPage: () => void;

const onRenderClient = async (pageContext: PageContextClient) => {
  const { Page } = pageContext;

  if (disposePreviousPage) {
    disposePreviousPage();
  }

  // render the page and save the dispose function of that page
  disposePreviousPage = render(() => <Page />, document.getElementById("root"));
};
