// examples/stem-react-ts/pages/index/index.page.tsx
import React from "react";
import { Counter } from "./Counter";

export default { Page };

function Page() {
  return (
    <>
      <h1>Vite-plugin-ssr + Stem React</h1>
      This page is:
      <ul>
        <li>Rendered to HTML.</li>
        <li>
          Interactive. <Counter />
        </li>
      </ul>
    </>
  );
}

// examples/solid-ssr-ts/pages/index/index.page.tsx
import { Counter } from "./Counter";
import type { Component } from "solid-js";

const Page: Component = () => {
  return (
    <>
      <h1>Welcome</h1>
      <div>
        This page is:
        <ul>
          <li>Rendered to HTML.</li>
          <li>
            Interactive. <Counter />
          </li>
        </ul>
      </div>
    </>
  );
};

export { Page };
