// examples/js-ssr-react-render-modes/src/pages/ssr/index.page.jsx
import { Counter } from "./Counter";
import "./index.css";

const Page = () => {
  return (
    <>
      <h1>SSR</h1>
      <p>This page is:</p>
      <ul>
        <li>Rendered to HTML and hydrated in the browser.</li>
        <li>
          Interactive. <Counter />
        </li>
      </ul>
      <p className="colored ssr">Blue text.</p>
    </>
  );
};

export { Page };

// examples/solid-ssr-ts/pages/index/index.page.tsx
import { Counter } from "./Counter";
import type { Component } from "solid-js";

const Page: Component = () => {
  return (
    <>
      <h1>Welcome</h1>
      <div>
        This page is:
        <ul>
          <li>Rendered to HTML.</li>
          <li>
            Interactive. <Counter />
          </li>
        </ul>
      </div>
    </>
  );
};

export { Page };
