// examples/ts-ssr-react-mui/src/pages/index/index.page.tsx
import { Counter } from "./Counter";
import Menu from "@mui/icons-material/Menu";
import Button from "@mui/material/Button";

const Page = () => {
  return (
    <>
      <h1>Welcome</h1>
      This page is:
      <ul>
        <li>Rendered to HTML.</li>
        <li>
          Interactive. <Counter />
        </li>
      </ul>
      <div>
        Menu: <Menu />
      </div>
      <div>
        Button: <Button>Some button</Button>
      </div>
    </>
  );
};

export { Page };

// examples/solid-ssr-ts/pages/index/index.page.tsx
import { Counter } from "./Counter";
import type { Component } from "solid-js";

const Page: Component = () => {
  return (
    <>
      <h1>Welcome</h1>
      <div>
        This page is:
        <ul>
          <li>Rendered to HTML.</li>
          <li>
            Interactive. <Counter />
          </li>
        </ul>
      </div>
    </>
  );
};

export { Page };
