// examples/solid-ssr-ts-v1/pages/index/+Page.tsx
import type { Component } from "solid-js";
import { Counter } from "./Counter";

const Page: Component = () => {
  return (
    <>
      <h1>Welcome</h1>
      <div>
        This page is:
        <ul>
          <li>Rendered to HTML.</li>
          <li>
            Interactive. <Counter />
          </li>
        </ul>
      </div>
    </>
  );
};
export default Page;

// examples/js-ssg-react-i18n-new/src/pages/index/+Page.jsx
import { useState } from "react";
import { locales } from "../../locales";
import { Link } from "../../renderer/Link";
import { LocaleText } from "../../renderer/LocaleText";

const Page = () => {
  return (
    <>
      <h1>
        <LocaleText>Welcome</LocaleText>
      </h1>
      <LocaleText>This page is</LocaleText>:
      <ul>
        <li>
          <LocaleText>Localized</LocaleText>.{" "}
          <LocaleText>Change language</LocaleText>:{" "}
          {locales.map((locale) => (
            <Link
              locale={locale}
              href="/"
              key={locale}
              style={{ marginLeft: 7 }}
            >
              {locale}
            </Link>
          ))}
        </li>
        <li>
          <LocaleText>Rendered to HTML</LocaleText>
        </li>
        <li>
          <LocaleText>Interactive</LocaleText> <Counter />
        </li>
      </ul>
    </>
  );
};

const Counter = () => {
  const [count, setCount] = useState(0);
  return (
    <button type="button" onClick={() => setCount((count) => count + 1)}>
      <LocaleText>Counter</LocaleText> {count}
    </button>
  );
};

export default Page;
