// examples/solid-spa/renderer/types.ts
import type {
  PageContextBuiltIn,
  /*
  // When using Client Routing https://vite-plugin-ssr.com/clientRouting
  PageContextBuiltInClientWithClientRouting as PageContextBuiltInClient
  /*/
  // When using Server Routing
  PageContextBuiltInClientWithServerRouting as PageContextBuiltInClient,
  //*/
} from "vite-plugin-ssr/types";
import type { Component } from "solid-js";

type Page = Component<PageProps>;
type PageProps = {};

export type PageContextCustom = {
  Page: Page;
  pageProps?: PageProps;
};

type PageContextServer = PageContextBuiltIn<Page> & PageContextCustom;
type PageContextClient = PageContextBuiltInClient<Page> & PageContextCustom;

type PageContextCommon = PageContextClient | PageContextServer;

export type {
  PageContextServer,
  PageContextClient,
  PageContextCommon,
  PageProps,
};

// examples/ts-ssr-react-redux-toolkit/src/renderer/types.ts
import React from "react";
import type {
  PageContextBuiltIn,
  /*
// When using Client Routing https://vite-plugin-ssr.com/clientRouting
PageContextBuiltInClientWithClientRouting as PageContextBuiltInClient
/*/
  // When using Server Routing
  PageContextBuiltInClientWithServerRouting as PageContextBuiltInClient,
} from "vite-plugin-ssr/types";
import { CounterState } from "./counterSlice";

type PageProps = Record<string, unknown>;
type Page = (pageProps: PageProps) => React.JSX.Element;

type PageContextCustom = {
  Page: Page;
  pageProps?: PageProps;
  urlPathname: string;
  pageHtml: string;
  PRELOADED_STATE: CounterState;
};

type PageContextServer = PageContextBuiltIn<Page> & PageContextCustom;
type PageContextClient = PageContextBuiltInClient<Page> & PageContextCustom;

type PageContext = PageContextClient | PageContextServer;

export type {
  PageContext,
  PageContextClient,
  PageContextCustom,
  PageContextServer,
  PageProps,
};
